### ISSUE TITLE
Missing eval_data Attribute in Argument Parser – Error When Running etth1.sh Script

### ISSUE THREAD

**Issue by cccccrj** [DC-research/TEMPO#8]
When running the `etth1.sh` script in your `scripts` folder, I encountered the following error:

```bash
Namespace(batch_size=256, c_out=1, checkpoints='./lora_revin_6domain_checkpoints_1/', config_path='./configs/multiple_datasets.yml', cos=1, d_ff=768, d_model=768, datasets='ETTm1,ETTh2,ETTm2,electricity,traffic,weather', decay_fac=0.5, dropout=0.3, e_layers=3, electri_multiplier=1, embed='timeF', enc_in=7, equal=1, freeze=1, gpt_layers=6, hid_dim=16, is_gpt=1, itr=1, kernel_size=25, label_len=168, learning_rate=0.001, loss_func='mse', lradj='type3', max_len=-1, model='TEMPO', model_id='etth1_TEMPO_6_prompt_learn_336_96_100', n_heads=4, no_stl_loss=False, num_nodes=1, num_workers=0, patch_size=16, patience=5, pool=False, pred_len=96, pretrain=1, prompt=1, seq_len=336, stl_weight=0.001, stride=8, target_data='ETTh1', task_name='long_term_forecast', tmax=20, traffic_multiplier=1, train_epochs=10, use_token=0)
Traceback (most recent call last):
  File "main_multi_6domain_release.py", line 252, in <module>
    train_data, train_loader, test_data, test_loader, vali_data, vali_loader = prepare_data_loaders(args, config)
  File "main_multi_6domain_release.py", line 88, in prepare_data_loaders
    for dataset_name in args.eval_data.split(','):  
AttributeError: 'Namespace' object has no attribute 'eval_data'
```

I then checked the `argparse` module's help information but could not find any reference to `eval_data`. Could you provide some guidance on how to resolve this issue?

---

**Comment by idevede** [comment]
Thanks for your interest!

The eval_data attribute has been restored in the latest code update. We have updated it! Please let us know if you encounter any other issues.

Best
